# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://cornell-pl.github.io/"

relativeurls = true
canonifyurls = true

# Title of your site
title = "Cornell PL"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; TODO"

theme = "academic"
enableEmoji = false
footnotereturnlinkcontents = "<sup>↩</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
  noreferrerLinks = true

[params]
  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
  color_theme = "cornell"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Your details.
  name = "Cornell PL"
  canonical_url = "https://cornell-pl.github.io/"

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = ""  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = ""
  address = ""
  office_hours = ""
  phone = ""
  skype = ""
  telegram = ""
  keybase = ""

  # Diplay a logo in navigation bar rather than title (optional).  To enable,
  # place an image in `static/img/` and reference its filename below. To
  # disable, set the value to "".
  logo = ""

  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"
  reading_time = true
  comment_count = false
  section_pager = false
  math = false

  highlight = true
  highlight_languages = []
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = false

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  [params.talks]
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Faculty"
  url = "#faculty"
  weight = 5

[[menu.main]]
  name = "Students"
  url = "#students"
  weight = 6

[[menu.main]]
  name = "Alumni"
  url = "#alumni"
  weight = 10

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"
