name: Hugo deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.49.2'

      - name: Build website
        run: hugo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{github.event_name=='push' && github.ref=='refs/heads/master'}}
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public
      - run: ls -R
      - name: rsync
        env:
          DEPLOY_HOST: cslinux.cs.cornell.edu
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          DEPLOY_SRC: ./public/
          DEPLOY_DEST: /research/pl
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          rsync --compress --recursive --checksum --itemize-changes --delete \
            --chmod=Du=rwx,Dgo=rx,Fu=rw,Fog=r \
            -e "ssh -i pk -o 'UserKnownHostsFile kh'" \
            $DEPLOY_SRC $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DEST
